### ISSUE TITLE
docker搭建好以后访问403或404错误

### ISSUE THREAD

**Issue by glo0m7** [sco4x0/huwangbei2018_easy_laravel#1]
2018/10/23 18:39:05 [crit] 46#46: *5 stat() "/usr/share/nginx/html/public/index.php" failed (13: Permission denied), client: 172.18.0.1, server: _, request: "GET /index.php HTTP/1.1", host: "127.0.0.1"
WWW目录权限不够
进docker内改完权限才能访问

**Comment by sco4x0** [comment]
线上我就是直接用这个跑的，而且本地我也没能复现这个错，有改动过Dockerfile吗？ 可以再放点更详细的信息看看

**Comment by glo0m7** [comment]
今天恢复快照试了下又没问题了。。。昨天晚上构建了几次一直进不去
